### ISSUE TITLE
Incorrect URN syntax in python script.  

### ISSUE THREAD

**Issue by dpsnowden** [GCOOS/csv2nc#8]
See [line 60 in the python script](https://github.com/GCOOS/csv2nc/blob/master/bin/generate_gcoos_nc_timeseries_ocn.py#L60).  The URN syntax described in the [IOOS convention](http://ioos.github.io/conventions-for-observing-asset-identifiers/ioos_assets_wiki_init_v0_1/#informative-examples:ebe5944de060b6752ee4a92e470e3ed5) and in the OGC [best practice doc](http://portal.opengeospatial.org/files/?artifact_id=30575) require the first element of the URN to be literally `urn:`.

**Comment by fgayanilo** [comment]
acknowledged, script corrected
